### ISSUE TITLE
Checklist for release

### ISSUE THREAD

**Issue by Nemmo** [Nemmo/yii2-attachments#36]
Features, bugs and enhancements:
- [ ] Test correct saving of the files with hieroglyphs (like Chinese)
- [ ] All file manipulations works via AJAX
- [ ] 100% code coverage by tests
- [ ] Configurable upload and temp path per model (issue #32)
- [ ] Solve a problem with removing files and adding another few before first submit (issue #17)

**Comment by uldisn** [comment]
Other similar extension:  [d3files](https://github.com/d3yii2/d3files)
